# Generated by Django 4.2.5 on 2023-10-04 16:10

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazar',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(max_length=120)),
                ('stadium', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(default='club_image.jpg', upload_to='news_club_images/')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Kulüp',
                'verbose_name_plural': 'Kulüp',
                'db_table': 'Club',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=120)),
                ('image', models.ImageField(default='coach_image.jpg', upload_to='news_coach_images/')),
            ],
            options={
                'verbose_name': 'Teknik Direktör',
                'verbose_name_plural': 'Teknik Direktör',
                'db_table': 'Coach',
            },
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(default='league_image.jpg', upload_to='news_league_images/')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
                ('history', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Ligler',
                'verbose_name_plural': 'Ligler',
                'db_table': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(default='league_image.jpg', upload_to='news_nationality_images/')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Ülke',
                'verbose_name_plural': 'Ülke',
                'db_table': 'Nationality',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=120)),
                ('foot', models.CharField(max_length=120)),
                ('size', models.FloatField()),
                ('weight', models.PositiveIntegerField()),
                ('numbers', models.PositiveIntegerField()),
                ('image', models.ImageField(default='player_image.jpg', upload_to='news_player_images/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp', to='mackolik.club')),
            ],
            options={
                'verbose_name': 'Oyuncu',
                'verbose_name_plural': 'Oyuncu',
                'db_table': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=120)),
                ('image', models.ImageField(default='referee_image.jpg', upload_to='news_referee_images/')),
            ],
            options={
                'verbose_name': 'Hakem',
                'verbose_name_plural': 'Hakem',
                'db_table': 'Referee',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('ok', models.ManyToManyField(related_name='oynadıgı_kulup', to='mackolik.club')),
                ('player', models.ManyToManyField(related_name='oyuncu', to='mackolik.player')),
                ('tok', models.ManyToManyField(related_name='transfer_oldugu_kulup', to='mackolik.club')),
            ],
            options={
                'verbose_name': 'Transferler',
                'verbose_name_plural': 'Transferler',
                'db_table': 'Transfers',
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('om', models.PositiveIntegerField()),
                ('win', models.PositiveIntegerField()),
                ('draw', models.PositiveIntegerField()),
                ('lost', models.PositiveIntegerField()),
                ('goal', models.PositiveIntegerField()),
                ('puan', models.PositiveIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulup', to='mackolik.club')),
            ],
            options={
                'verbose_name': 'Puan Durumu',
                'verbose_name_plural': 'Puan Durumu',
                'db_table': 'Standings',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(max_length=300)),
                ('contents', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='news_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazar', to='mackolik.author')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('stadium', models.CharField(max_length=120)),
                ('skor', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='league', unique=True)),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp1', to='mackolik.club')),
                ('club1_team_line_up', models.ManyToManyField(blank=True, related_name='club1_mac_ilk_11', to='mackolik.player')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp2', to='mackolik.club')),
                ('club2_team_line_up', models.ManyToManyField(blank=True, related_name='club2_mac_ilk_11', to='mackolik.player')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lig', to='mackolik.leagues')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hakem', to='mackolik.referee')),
            ],
            options={
                'verbose_name': 'Maçlar',
                'verbose_name_plural': 'Maçlar',
                'db_table': 'Matches',
            },
        ),
        migrations.AddField(
            model_name='leagues',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ulke', to='mackolik.nationality'),
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='mackolik.leagues')),
            ],
            options={
                'verbose_name': 'Kupa',
                'verbose_name_plural': 'Kupa',
                'db_table': 'Cup',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp', to='mackolik.coach'),
        ),
        migrations.AddField(
            model_name='club',
            name='cup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kupa', to='mackolik.cup'),
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ligler', to='mackolik.leagues'),
        ),
    ]
