# Generated by Django 4.2.5 on 2023-09-27 11:04

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazar',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='newsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='isim', unique=True)),
            ],
            options={
                'verbose_name': 'Haber Kategorisi',
                'verbose_name_plural': 'Haber Kategorileri',
                'db_table': 'NewsCategories',
            },
        ),
        migrations.AlterField(
            model_name='matches',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='league', unique=True),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(max_length=300)),
                ('contents', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='baslik', unique=True)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='news_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='mackolik.newscategory')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
                'db_table': 'News',
            },
        ),
    ]
