# Generated by Django 4.2.6 on 2023-10-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='leagues',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='nationality',
        ),
        migrations.AddField(
            model_name='club',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_nationality', to='mackolik.nationality'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coach_nationality', to='mackolik.nationality'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_nationality', to='mackolik.nationality'),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_nationality', to='mackolik.nationality'),
        ),
        migrations.AddField(
            model_name='referee',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_nationality', to='mackolik.nationality'),
        ),
    ]
