# Generated by Django 4.2.5 on 2023-09-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='puan',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
