# Generated by Django 4.2.5 on 2023-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='skor',
            new_name='club1_skor',
        ),
        migrations.AddField(
            model_name='matches',
            name='club2_skor',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
