# Generated by Django 4.2.5 on 2023-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=120)),
                ('image', models.ImageField(default='coach_image.jpg', upload_to='news_coach_images/')),
            ],
            options={
                'verbose_name': 'Teknik Direktör',
                'verbose_name_plural': 'Teknik Direktör',
                'db_table': 'Coach',
            },
        ),
    ]
