# Generated by Django 4.2.6 on 2023-10-10 12:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True),
        ),
    ]
