# Generated by Django 4.2.5 on 2023-10-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'verbose_name': 'Ülke', 'verbose_name_plural': 'Ülke'},
        ),
        migrations.AlterModelTable(
            name='nationality',
            table='Nationality',
        ),
    ]
