# Generated by Django 4.2.5 on 2023-09-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='mackolik.leagues')),
            ],
            options={
                'verbose_name': 'Kupa',
                'verbose_name_plural': 'Kupa',
                'db_table': 'Cup',
            },
        ),
    ]
