# Generated by Django 4.2.6 on 2024-01-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.club', verbose_name='Kulüp')),
                ('cup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.cup', verbose_name='Kupa')),
            ],
            options={
                'verbose_name': 'Kulüp Kupaları',
                'verbose_name_plural': 'Kulüp Kupaları',
                'db_table': 'ClubCups',
            },
        ),
    ]
