# Generated by Django 4.2.5 on 2023-09-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0002_cup'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='kupa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kupa', to='mackolik.cup'),
        ),
    ]
