# Generated by Django 4.2.5 on 2023-09-27 11:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0002_author_newscategory_alter_matches_slug_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='title', unique=True),
        ),
        migrations.DeleteModel(
            name='newsCategory',
        ),
    ]
