# Generated by Django 4.2.6 on 2023-10-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0002_remove_club_nationality_remove_coach_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='ok',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='player',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='tok',
        ),
        migrations.AddField(
            model_name='transfers',
            name='ok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_club', to='mackolik.club'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_transfer', to='mackolik.player'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='tok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_o_club', to='mackolik.club'),
        ),
    ]
