# Generated by Django 4.2.6 on 2024-01-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0002_clubcups'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcups',
            name='piece',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
