# Generated by Django 4.2.5 on 2023-09-12 11:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0002_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1200, unique=True)),
                ('country', models.CharField(max_length=120)),
                ('stadium', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(default='club_image.jpg', upload_to='news_club_images/')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teknik_Direktör', to='mackolik.coach')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ligler', to='mackolik.leagues')),
            ],
            options={
                'verbose_name': 'Kulüp',
                'verbose_name_plural': 'Kulüp',
                'db_table': 'Club',
            },
        ),
    ]
