# Generated by Django 4.2.5 on 2023-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0002_alter_nationality_options_alter_nationality_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='history',
            field=models.TextField(null=True),
        ),
    ]
