# Generated by Django 4.2.5 on 2023-09-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0003_club_kupa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='kupa',
            new_name='cup',
        ),
    ]
