# Generated by Django 4.2.5 on 2023-10-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0003_player_pozition'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='club1_team_goals',
            field=models.ManyToManyField(blank=True, related_name='club1_mac_goller', to='mackolik.player'),
        ),
        migrations.AddField(
            model_name='matches',
            name='club1_team_reserves',
            field=models.ManyToManyField(blank=True, related_name='club1_mac_yedekler', to='mackolik.player'),
        ),
        migrations.AddField(
            model_name='matches',
            name='club2_team_goals',
            field=models.ManyToManyField(blank=True, related_name='club2_mac_goller', to='mackolik.player'),
        ),
        migrations.AddField(
            model_name='matches',
            name='club2_team_reserves',
            field=models.ManyToManyField(blank=True, related_name='club2_mac_yedekler', to='mackolik.player'),
        ),
    ]
