# Generated by Django 4.2.6 on 2023-10-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0003_remove_transfers_ok_remove_transfers_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.player')),
            ],
            options={
                'verbose_name': 'Oyuncu Geçmiş Kulüpleri',
                'verbose_name_plural': 'Oyuncu Geçmiş Kulüpleri',
                'db_table': 'PlayerClubHistory',
            },
        ),
    ]
