# Generated by Django 4.2.5 on 2023-09-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0003_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=120)),
                ('foot', models.CharField(max_length=120)),
                ('size', models.FloatField()),
                ('weight', models.PositiveIntegerField()),
                ('numbers', models.PositiveIntegerField()),
                ('image', models.ImageField(default='player_image.jpg', upload_to='news_player_images/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp', to='mackolik.club')),
            ],
            options={
                'verbose_name': 'Oyuncu',
                'verbose_name_plural': 'Oyuncu',
                'db_table': 'Player',
            },
        ),
    ]
