# Generated by Django 4.2.5 on 2023-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0004_matches_club1_team_goals_matches_club1_team_reserves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='man_of_the_match',
            field=models.ManyToManyField(blank=True, related_name='maçın_adamı', to='mackolik.player'),
        ),
    ]
