# Generated by Django 4.2.5 on 2023-09-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0004_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp', to='mackolik.coach'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
