# Generated by Django 4.2.5 on 2023-09-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0004_rename_kupa_club_cup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('ok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oynadıgı_kulup', to='mackolik.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyuncu', to='mackolik.player')),
                ('tok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_oldugu_kulup', to='mackolik.club')),
            ],
            options={
                'verbose_name': 'Transferler',
                'verbose_name_plural': 'Transferler',
                'db_table': 'Transfers',
            },
        ),
    ]
