# Generated by Django 4.2.6 on 2023-10-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0004_playerclubhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='history_clubs',
            field=models.ManyToManyField(through='mackolik.PlayerClubHistory', to='mackolik.club'),
        ),
    ]
