# Generated by Django 4.2.6 on 2023-12-26 20:59

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mackolik', '0005_player_history_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(verbose_name='Hakkında'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.coach', verbose_name='Teknik Direktör'),
        ),
        migrations.AlterField(
            model_name='club',
            name='cup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kupa', to='mackolik.cup', verbose_name='Kupa'),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='club_image.jpg', upload_to='news_club_images/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.leagues', verbose_name='Lig'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.nationality', verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.CharField(max_length=120, unique=True, verbose_name='Staydum'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(default='coach_image.jpg', upload_to='news_coach_images/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.nationality', verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='mackolik.leagues', verbose_name='Lig'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='history',
            field=models.TextField(null=True, verbose_name='Tarihçe'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='image',
            field=models.ImageField(default='league_image.jpg', upload_to='news_league_images/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.nationality', verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp1', to='mackolik.club', verbose_name='Kulüp 1'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club1_skor',
            field=models.CharField(max_length=120, verbose_name='Kulüp 1 Skor'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club1_team_goals',
            field=models.ManyToManyField(blank=True, related_name='club1_mac_goller', to='mackolik.player', verbose_name='Kulüp 1 Goller'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club1_team_line_up',
            field=models.ManyToManyField(blank=True, related_name='club1_line_up', to='mackolik.player', verbose_name='Kulüp 1 İlk 11'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club1_team_reserves',
            field=models.ManyToManyField(blank=True, to='mackolik.player', verbose_name='Kulüp 1 Yedekler'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp2', to='mackolik.club', verbose_name='Kulüp 2'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club2_skor',
            field=models.CharField(max_length=120, null=True, verbose_name='Kulüp 2 Skor'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club2_team_goals',
            field=models.ManyToManyField(blank=True, related_name='club2_mac_goller', to='mackolik.player', verbose_name='Kulüp 2 Goller'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club2_team_line_up',
            field=models.ManyToManyField(blank=True, related_name='club2_mac_ilk_11', to='mackolik.player', verbose_name='Kulüp 2 İlk 11'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='club2_team_reserves',
            field=models.ManyToManyField(blank=True, related_name='club2_mac_yedekler', to='mackolik.player', verbose_name='Kulüp 2 Yedekler'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lig', to='mackolik.leagues', verbose_name='Lig'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='man_of_the_match',
            field=models.ManyToManyField(blank=True, related_name='maçın_adamı', to='mackolik.player', verbose_name='Maçın Adamı'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.referee', verbose_name='Hakem'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='stadium',
            field=models.CharField(max_length=120, verbose_name='Stadyum'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='time',
            field=models.FloatField(verbose_name='Maç Saati'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='image',
            field=models.ImageField(default='league_image.jpg', upload_to='news_nationality_images/', verbose_name='Bayrak'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.author', verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='contents',
            field=models.TextField(verbose_name='Haber'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='news_images/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(max_length=300, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.CharField(max_length=120, verbose_name='Ayak'),
        ),
        migrations.AlterField(
            model_name='player',
            name='history_clubs',
            field=models.ManyToManyField(through='mackolik.PlayerClubHistory', to='mackolik.club', verbose_name='Geçmiş külüpleri'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='player_image.jpg', upload_to='news_player_images/', verbose_name='resim'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.nationality', verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='player',
            name='numbers',
            field=models.PositiveIntegerField(verbose_name='Numara'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pozition',
            field=models.CharField(max_length=20, null=True, verbose_name='Oynadığı Pozisyon'),
        ),
        migrations.AlterField(
            model_name='player',
            name='size',
            field=models.FloatField(verbose_name='Boy'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Kilo'),
        ),
        migrations.AlterField(
            model_name='playerclubhistory',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.club', verbose_name=' Kulüp'),
        ),
        migrations.AlterField(
            model_name='playerclubhistory',
            name='end_date',
            field=models.DateField(verbose_name='Sözleşme nin Bittiği Tarih'),
        ),
        migrations.AlterField(
            model_name='playerclubhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.player', verbose_name='Oyuncu'),
        ),
        migrations.AlterField(
            model_name='playerclubhistory',
            name='start_date',
            field=models.DateField(verbose_name='Transfer Olduğu Tarih'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='image',
            field=models.ImageField(default='referee_image.jpg', upload_to='news_referee_images/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.nationality', verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.club', verbose_name='Kulüp'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='draw',
            field=models.PositiveIntegerField(verbose_name='Beraberlik'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='goal',
            field=models.PositiveIntegerField(verbose_name='Atılan Gol'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='lost',
            field=models.PositiveIntegerField(verbose_name='Kaybedilen Maç'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='om',
            field=models.PositiveIntegerField(verbose_name='Oynanan Maç'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='puan',
            field=models.PositiveIntegerField(verbose_name='Puan'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='win',
            field=models.PositiveIntegerField(verbose_name='Kazanılan Maç'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='ok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_club', to='mackolik.club', verbose_name='Oynadığı Kulüp'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.player', verbose_name='Oyuncu'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='time',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='tok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.club', verbose_name='Transfer Olduğu Kulüp'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('favorite_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mackolik.club', verbose_name='Favori Kulüp')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
