# Generated by Django 4.2.5 on 2023-09-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0005_alter_club_coach_alter_club_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('stadium', models.CharField(max_length=120)),
                ('skor', models.CharField(max_length=120)),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp1', to='mackolik.club')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulüp2', to='mackolik.club')),
            ],
            options={
                'verbose_name': 'Maçlar',
                'verbose_name_plural': 'Maçlar',
                'db_table': 'Matches',
            },
        ),
    ]
