# Generated by Django 4.2.5 on 2023-09-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0005_transfers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='ok',
        ),
    ]
