# Generated by Django 4.2.6 on 2023-12-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0006_alter_author_about_alter_author_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
