# Generated by Django 4.2.5 on 2023-09-12 14:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0006_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True),
        ),
    ]
