# Generated by Django 4.2.5 on 2023-09-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0007_matches_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='match',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='maç', to='mackolik.matches'),
        ),
    ]
