# Generated by Django 4.2.6 on 2024-01-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0007_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_rent', models.CharField(max_length=120, verbose_name='Kiralık')),
                ('testimonial', models.CharField(max_length=120, verbose_name='Bonservis')),
                ('free', models.CharField(max_length=120, verbose_name='Serbest')),
            ],
            options={
                'verbose_name': 'Kontrat',
                'verbose_name_plural': 'Kontratlar',
                'db_table': 'Contrat',
            },
        ),
        migrations.AddField(
            model_name='transfers',
            name='contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mackolik.contrat', verbose_name='Kontrat'),
        ),
    ]
