# Generated by Django 4.2.5 on 2023-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0007_transfers_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='team_line_up',
            field=models.ManyToManyField(blank=True, related_name='mac_ilk_11', to='mackolik.player'),
        ),
    ]
