# Generated by Django 4.2.6 on 2024-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0008_contrat_transfers_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='for_rent',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='free',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='contrat',
            name='contrat',
            field=models.CharField(max_length=120, null=True, verbose_name='Kontrat'),
        ),
    ]
