# Generated by Django 4.2.5 on 2023-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0008_matches_team_line_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='team_line_up',
        ),
        migrations.AddField(
            model_name='matches',
            name='club1_team_line_up',
            field=models.ManyToManyField(blank=True, related_name='club1_mac_ilk_11', to='mackolik.player'),
        ),
        migrations.AddField(
            model_name='matches',
            name='club2_team_line_up',
            field=models.ManyToManyField(blank=True, related_name='club2_mac_ilk_11', to='mackolik.player'),
        ),
    ]
