# Generated by Django 4.2.6 on 2024-01-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0009_remove_contrat_for_rent_remove_contrat_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Maç Saati'),
        ),
    ]
