# Generated by Django 4.2.5 on 2023-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackolik', '0009_remove_matches_team_line_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='nationality',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='ok',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='player',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='tok',
        ),
        migrations.AddField(
            model_name='transfers',
            name='ok',
            field=models.ManyToManyField(null=True, related_name='oynadıgı_kulup', to='mackolik.club'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='player',
            field=models.ManyToManyField(related_name='oyuncu', to='mackolik.player'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='tok',
            field=models.ManyToManyField(related_name='transfer_oldugu_kulup', to='mackolik.club'),
        ),
    ]
